//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Light.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RE() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Light.Data.RE", typeof(RE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 聚合函数字段{0}已存在 的本地化字符串。
        /// </summary>
        internal static string AggregateFunctionFieldIsExists {
            get {
                return ResourceManager.GetString("AggregateFunctionFieldIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汇总类型非指定的类型{0} 的本地化字符串。
        /// </summary>
        internal static string AggregateTypeIsNotSpecifyType {
            get {
                return ResourceManager.GetString("AggregateTypeIsNotSpecifyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计字段类型不合法 的本地化字符串。
        /// </summary>
        internal static string AggregationFieldIsInvaild {
            get {
                return ResourceManager.GetString("AggregationFieldIsInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计映射表中没有统计字段 的本地化字符串。
        /// </summary>
        internal static string AggregationFieldsIsNotExists {
            get {
                return ResourceManager.GetString("AggregationFieldsIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计映射不能进行单列查询操作 的本地化字符串。
        /// </summary>
        internal static string AggregationMappingCanNotSelectSingle {
            get {
                return ResourceManager.GetString("AggregationMappingCanNotSelectSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计表关联错误 的本地化字符串。
        /// </summary>
        internal static string AggregationMappingRelateError {
            get {
                return ResourceManager.GetString("AggregationMappingRelateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计结果为空 的本地化字符串。
        /// </summary>
        internal static string AggregationResultIsNull {
            get {
                return ResourceManager.GetString("AggregationResultIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复合字段没有子字段 的本地化字符串。
        /// </summary>
        internal static string ComplexFieldHaveNotSubFields {
            get {
                return ResourceManager.GetString("ComplexFieldHaveNotSubFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot;的数据字段&quot;{1}&quot;不存在 的本地化字符串。
        /// </summary>
        internal static string ConfigDataFieldIsNotExists {
            get {
                return ResourceManager.GetString("ConfigDataFieldIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot;的数据字段名为空值 的本地化字符串。
        /// </summary>
        internal static string ConfigDataFieldNameIsEmpty {
            get {
                return ResourceManager.GetString("ConfigDataFieldNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置数据读取出错,数据节点并非&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string ConfigDataLoadError {
            get {
                return ResourceManager.GetString("ConfigDataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置数据类型{0}的值为空 的本地化字符串。
        /// </summary>
        internal static string ConfigDataTypeValueIsEmpty {
            get {
                return ResourceManager.GetString("ConfigDataTypeValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接配置不存在 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettingIsNotExists {
            get {
                return ResourceManager.GetString("ConnectionSettingIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接配置名&quot;{0}&quot;不存在 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettingNameIsNotExists {
            get {
                return ResourceManager.GetString("ConnectionSettingNameIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该数据库不支持内分页 的本地化字符串。
        /// </summary>
        internal static string DataBaseNotSupportInnerPage {
            get {
                return ResourceManager.GetString("DataBaseNotSupportInnerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据连接上下文不存在 的本地化字符串。
        /// </summary>
        internal static string DataContextIsNotExists {
            get {
                return ResourceManager.GetString("DataContextIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据映射表中没设定数据字段 的本地化字符串。
        /// </summary>
        internal static string DataFieldsIsNotExists {
            get {
                return ResourceManager.GetString("DataFieldsIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据表与统计字段不匹配 的本地化字符串。
        /// </summary>
        internal static string DataMappingIsNotMatchAggregateField {
            get {
                return ResourceManager.GetString("DataMappingIsNotMatchAggregateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的查询表与统计表达式不匹配 的本地化字符串。
        /// </summary>
        internal static string DataMappingIsNotMatchAggregationExpression {
            get {
                return ResourceManager.GetString("DataMappingIsNotMatchAggregationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的查询表与排序表达式不匹配 的本地化字符串。
        /// </summary>
        internal static string DataMappingIsNotMatchOrderExpression {
            get {
                return ResourceManager.GetString("DataMappingIsNotMatchOrderExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的查询表与查询表达式不匹配 的本地化字符串。
        /// </summary>
        internal static string DataMappingIsNotMatchQueryExpression {
            get {
                return ResourceManager.GetString("DataMappingIsNotMatchQueryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式的查询表不一致 的本地化字符串。
        /// </summary>
        internal static string DataMappingOfExpressionIsNotMatch {
            get {
                return ResourceManager.GetString("DataMappingOfExpressionIsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据表不允许多少自增字段 的本地化字符串。
        /// </summary>
        internal static string DataTableNotAllowMoreIdentityField {
            get {
                return ResourceManager.GetString("DataTableNotAllowMoreIdentityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据表没有指定自增ID 的本地化字符串。
        /// </summary>
        internal static string DataTableNotIdentityField {
            get {
                return ResourceManager.GetString("DataTableNotIdentityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的值不能为空值 的本地化字符串。
        /// </summary>
        internal static string DataValueIsNotAllowEmply {
            get {
                return ResourceManager.GetString("DataValueIsNotAllowEmply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态汇总字段不存在 的本地化字符串。
        /// </summary>
        internal static string DynamicAggregateFieldIsNotExists {
            get {
                return ResourceManager.GetString("DynamicAggregateFieldIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据枚举值不允许为0 的本地化字符串。
        /// </summary>
        internal static string EnumerableLengthNotAllowIsZero {
            get {
                return ResourceManager.GetString("EnumerableLengthNotAllowIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段数据映射类型不匹配 的本地化字符串。
        /// </summary>
        internal static string FieldIsNotMatchDataMapping {
            get {
                return ResourceManager.GetString("FieldIsNotMatchDataMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射字段{0}不存在 的本地化字符串。
        /// </summary>
        internal static string FieldMappingIsNotExists {
            get {
                return ResourceManager.GetString("FieldMappingIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段名称&quot;{0}&quot;不合法 的本地化字符串。
        /// </summary>
        internal static string FieldNameIsInvalid {
            get {
                return ResourceManager.GetString("FieldNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组字段名{0}已存在 的本地化字符串。
        /// </summary>
        internal static string GroupNameFieldIsExists {
            get {
                return ResourceManager.GetString("GroupNameFieldIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入值不允许为空值 的本地化字符串。
        /// </summary>
        internal static string InputValueIsNotAllowNull {
            get {
                return ResourceManager.GetString("InputValueIsNotAllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载数据表配置失败 的本地化字符串。
        /// </summary>
        internal static string LoadDataTableConfigFaild {
            get {
                return ResourceManager.GetString("LoadDataTableConfigFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无定义数据映射特性 的本地化字符串。
        /// </summary>
        internal static string NotDefineDataMappingAttribute {
            get {
                return ResourceManager.GetString("NotDefineDataMappingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不在汇总字段中 的本地化字符串。
        /// </summary>
        internal static string NotExistsAggregateField {
            get {
                return ResourceManager.GetString("NotExistsAggregateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非原始字段不能使用单列查询 的本地化字符串。
        /// </summary>
        internal static string OnlyPrimitiveFieldCanSelectSingle {
            get {
                return ResourceManager.GetString("OnlyPrimitiveFieldCanSelectSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主键字段不存在 的本地化字符串。
        /// </summary>
        internal static string PrimaryKeyIsNotExist {
            get {
                return ResourceManager.GetString("PrimaryKeyIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机排序字段不存在 的本地化字符串。
        /// </summary>
        internal static string RandomOrderFieldIsNotExists {
            get {
                return ResourceManager.GetString("RandomOrderFieldIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机排序不允许做排序组合 的本地化字符串。
        /// </summary>
        internal static string RandomOrderForbitCatch {
            get {
                return ResourceManager.GetString("RandomOrderForbitCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取值范围数量值不合法 的本地化字符串。
        /// </summary>
        internal static string RegionSizeInvaild {
            get {
                return ResourceManager.GetString("RegionSizeInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取值范围开始值不合法 的本地化字符串。
        /// </summary>
        internal static string RegionStartInvaild {
            get {
                return ResourceManager.GetString("RegionStartInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联键值{0}并非原始数据字段 的本地化字符串。
        /// </summary>
        internal static string RelationKeyIsNotPrimitiveField {
            get {
                return ResourceManager.GetString("RelationKeyIsNotPrimitiveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联映射{0}不存在 的本地化字符串。
        /// </summary>
        internal static string RelationMappingIsNotExists {
            get {
                return ResourceManager.GetString("RelationMappingIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联映射主键已存在 的本地化字符串。
        /// </summary>
        internal static string RelationMasterKeyIsExists {
            get {
                return ResourceManager.GetString("RelationMasterKeyIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单列查询类型错误 的本地化字符串。
        /// </summary>
        internal static string SingleFieldSelectTypeError {
            get {
                return ResourceManager.GetString("SingleFieldSelectTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的类型并非统计表类型 的本地化字符串。
        /// </summary>
        internal static string TheDataMappingIsNotAggregationMapping {
            get {
                return ResourceManager.GetString("TheDataMappingIsNotAggregationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的类型并非实体表类型 的本地化字符串。
        /// </summary>
        internal static string TheDataMappingIsNotDataEntityMapping {
            get {
                return ResourceManager.GetString("TheDataMappingIsNotDataEntityMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的类型并非数据表类型 的本地化字符串。
        /// </summary>
        internal static string TheDataMappingIsNotDataTableMapping {
            get {
                return ResourceManager.GetString("TheDataMappingIsNotDataTableMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定表并非数据表,不能批量删除 的本地化字符串。
        /// </summary>
        internal static string TheDataMappingNotAllowDeleteMass {
            get {
                return ResourceManager.GetString("TheDataMappingNotAllowDeleteMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主键数目不匹配 的本地化字符串。
        /// </summary>
        internal static string TheNumberOfPrimaryKeysIsNotMatch {
            get {
                return ResourceManager.GetString("TheNumberOfPrimaryKeysIsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联类的集合类型非IList&lt;T&gt; 的本地化字符串。
        /// </summary>
        internal static string TheRelationTypeNotIList {
            get {
                return ResourceManager.GetString("TheRelationTypeNotIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计汇总字段类型不正确 的本地化字符串。
        /// </summary>
        internal static string TheTypeOfAggregationFieldIsNotRight {
            get {
                return ResourceManager.GetString("TheTypeOfAggregationFieldIsNotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段类型不正确 的本地化字符串。
        /// </summary>
        internal static string TheTypeOfDataFieldIsNotRight {
            get {
                return ResourceManager.GetString("TheTypeOfDataFieldIsNotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表的自增字段类型必须为Int32和Int64 的本地化字符串。
        /// </summary>
        internal static string TheTypeOfIdentityFieldError {
            get {
                return ResourceManager.GetString("TheTypeOfIdentityFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型{0}继承错误 的本地化字符串。
        /// </summary>
        internal static string TypeInheritError {
            get {
                return ResourceManager.GetString("TypeInheritError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型{0}并非数据库类型 的本地化字符串。
        /// </summary>
        internal static string TypeIsNotDatabase {
            get {
                return ResourceManager.GetString("TypeIsNotDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型{0}继承错误,并非继承自{1} 的本地化字符串。
        /// </summary>
        internal static string TypeNotInheritFromSpecialType {
            get {
                return ResourceManager.GetString("TypeNotInheritFromSpecialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该类型字段不支持{0}转换 的本地化字符串。
        /// </summary>
        internal static string TypeUnsupportTheTransform {
            get {
                return ResourceManager.GetString("TypeUnsupportTheTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段{0}非字符类型 的本地化字符串。
        /// </summary>
        internal static string TypfOfDataFieldIsNotString {
            get {
                return ResourceManager.GetString("TypfOfDataFieldIsNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的排序格式 的本地化字符串。
        /// </summary>
        internal static string UnknowOrderType {
            get {
                return ResourceManager.GetString("UnknowOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持日期格式{0} 的本地化字符串。
        /// </summary>
        internal static string UnsupportDateFormat {
            get {
                return ResourceManager.GetString("UnsupportDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持谓词{0}的查询 的本地化字符串。
        /// </summary>
        internal static string UnSupportPredicate {
            get {
                return ResourceManager.GetString("UnSupportPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新字段不存在 的本地化字符串。
        /// </summary>
        internal static string UpdateFieldIsNotExists {
            get {
                return ResourceManager.GetString("UpdateFieldIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新字段类型出错, 的本地化字符串。
        /// </summary>
        internal static string UpdateFieldTypeIsError {
            get {
                return ResourceManager.GetString("UpdateFieldTypeIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值&quot;{0}&quot;不存在与枚举集合{1}中 的本地化字符串。
        /// </summary>
        internal static string ValueNotInEnumType {
            get {
                return ResourceManager.GetString("ValueNotInEnumType", resourceCulture);
            }
        }
    }
}
